version: '3.7'

services:
    # MySQL
    db-mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: classting-db
        env_file: .env
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always
