version: '3.7'

services:
    # MySQL
    db-mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: codecamp-teamproject-db
        env_file: ./backend/.env
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # Redis
    db-redis:
        image: redis:latest
        container_name: codecamp-teamproject-redis
        ports:
            - 6379:6379
        restart: always
