version: '3.7'

services:
    # MySQL
    db-mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: classting-db
        env_file: .env.stage
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/init:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        restart: always

    # NestJS
    backend:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .

        container_name: classting-backend

        ports:
            - 80:3001

        # 환경 변수 설정
        env_file: .env.stage

        # 재시작 설정
        restart: always
