version: '3.7'

services:
    # MySQL
    db-mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: classting-db
        env_file: .env
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # NestJS
    backend:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .

        container_name: classting-backend

        # Container Port 연결
        #   - host:container
        ports:
            - 3001:3001

        # 환경 변수 설정
        env_file: .env

        volumes:
            - ./src:/app/src
            - ./dist:/app/dist
            - ./test:/app/test
            - ./key:/app/key

            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./tsconfig.build.json:/app/tsconfig.build.json
            - ./tsconfig.json:/app/tsconfig.json

            - ./.env.dev:/app/.env

        # 재시작 설정
        restart: always
